# testnet or mainnet
TestNet = true

# Program home directory
HomeDir = "data"

# chain data directory
DataDir = ""

# Logging switch
FileLogging = true


# P2P configuration
#Externale ip (default = "0.0.0.0")
ExternalIp = "0.0.0.0"


# Custom bootstrap
#Bootstrap = ""

# P2P port (default = "33330")
P2pPort="33330"


# RPC configuration, (default = 33331)
RpcPort = "33331"
# RPC password
RpcPass = ""

# TLS switch
RpcTLS = false

# Roll back the node chain to a certain height, -1 means not roll back
FallBackTo = -1


# If it is a block generating node, it needs to be configured
# Json file address of the address private key
KeyFile = ""
# Password to decrypt the private key json file
KeyPass = ""

